### ISSUE TITLE
`rosdep update` needs to be run before `rosdep install ...`

### ISSUE THREAD

**Issue by mbilker** [Pitt-RAS/IARC7_ROS_Docker_Configurator#1]
After setting up a Docker container with `./build.sh` and `./create.sh`, I followed the [Setting up a workspace with `wstool`](https://github.com/Pitt-RAS/iarc7_common/wiki/Installation#setting-up-a-workspace-with-wstool) which errored on:
```
rosdep install --from-paths src --ignore-src --rosdistro=kinetic -y
```
because `rosdep update` had not been run.

Should this be run in the `Dockerfile` when building the image (`./build.sh`)?

**Comment by satorinin** [comment]
I added `RUN rosdep update` to the `Dockerfile` after it switches users

**Comment by mbilker** [comment]
That should do it.
